using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BQuery.SourceGenerators;

[Generator]
public sealed class JsInteropMethodsGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "BQuery.GenerateJsInteropMethodsAttribute";
    private const string JsModuleConstantsMetadataName = "BQuery.JsModuleConstants";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (generatorContext, _) => GetTarget(generatorContext))
            .Where(static target => target is not null);

        var combined = context.CompilationProvider.Combine(targets.Collect());

        context.RegisterSourceOutput(combined, static (productionContext, source) =>
        {
            var (compilation, targetInfos) = source;
            if (targetInfos.IsDefaultOrEmpty)
            {
                return;
            }

            var jsModuleConstantsSymbol = compilation.GetTypeByMetadataName(JsModuleConstantsMetadataName);
            if (jsModuleConstantsSymbol is null)
            {
                return;
            }

            foreach (var target in targetInfos.Distinct(TargetInfoComparer.Instance))
            {
                if (target is null)
                {
                    continue;
                }

                var generatedSource = GenerateSource(jsModuleConstantsSymbol, target);
                if (generatedSource is null)
                {
                    continue;
                }

                productionContext.AddSource(
                    $"{target.HintName}.JsInteropMethods.g.cs",
                    SourceText.From(generatedSource, Encoding.UTF8));
            }
        });
    }

    private static TargetInfo? GetTarget(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        foreach (var attribute in context.Attributes)
        {
            if (attribute.AttributeClass?.ToDisplayString() != AttributeMetadataName)
            {
                continue;
            }

            if (attribute.ConstructorArguments.Length != 1)
            {
                continue;
            }

            if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol constantsType)
            {
                continue;
            }

            return new TargetInfo(classSymbol, constantsType, GetHintName(classSymbol));
        }

        return null;
    }

    private static string? GenerateSource(INamedTypeSymbol jsModuleConstantsSymbol, TargetInfo target)
    {
        var methods = GetMethodMembers(target.ConstantsType);
        if (methods.Count == 0)
        {
            return null;
        }

        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat;
        var targetNamespace = target.ClassSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : target.ClassSymbol.ContainingNamespace.ToDisplayString();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");

        if (targetNamespace is not null)
        {
            builder.Append("namespace ").Append(targetNamespace).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("partial class ").Append(target.ClassSymbol.Name).AppendLine();
        builder.AppendLine("{");

        foreach (var methodName in methods)
        {
            builder.Append("    internal static readonly string ")
                .Append(methodName)
                .Append("Method = ")
                .Append(jsModuleConstantsSymbol.ToDisplayString(typeFormat))
                .Append(".GetMethod(")
                .AppendLine();
            builder.Append("        ")
                .Append(jsModuleConstantsSymbol.ToDisplayString(typeFormat))
                .Append(".ModuleName,")
                .AppendLine();
            builder.Append("        ")
                .Append(target.ConstantsType.ToDisplayString(typeFormat))
                .Append(".ModuleName,")
                .AppendLine();
            builder.Append("        ")
                .Append(target.ConstantsType.ToDisplayString(typeFormat))
                .Append(".")
                .Append(methodName)
                .Append(");")
                .AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static List<string> GetMethodMembers(INamedTypeSymbol constantsType)
    {
        var members = new List<string>();

        foreach (var member in constantsType.GetMembers())
        {
            if (member.Name == "ModuleName")
            {
                continue;
            }

            if (member is IFieldSymbol field && field.IsStatic && field.Type.SpecialType == SpecialType.System_String)
            {
                members.Add(field.Name);
                continue;
            }

            if (member is IPropertySymbol property && property.IsStatic && property.Type.SpecialType == SpecialType.System_String)
            {
                members.Add(property.Name);
            }
        }

        return members;
    }

    private static string GetHintName(INamedTypeSymbol classSymbol)
    {
        var parts = new Stack<string>();
        ISymbol? current = classSymbol;

        while (current is INamedTypeSymbol namedType)
        {
            parts.Push(namedType.Name);
            current = namedType.ContainingType;
        }

        if (!classSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            parts.Push(classSymbol.ContainingNamespace.ToDisplayString().Replace('.', '_'));
        }

        return string.Join(".", parts);
    }

    private sealed class TargetInfo
    {
        public TargetInfo(INamedTypeSymbol classSymbol, INamedTypeSymbol constantsType, string hintName)
        {
            ClassSymbol = classSymbol;
            ConstantsType = constantsType;
            HintName = hintName;
        }

        public INamedTypeSymbol ClassSymbol { get; }

        public INamedTypeSymbol ConstantsType { get; }

        public string HintName { get; }
    }

    private sealed class TargetInfoComparer : IEqualityComparer<TargetInfo?>
    {
        public static TargetInfoComparer Instance { get; } = new();

        public bool Equals(TargetInfo? x, TargetInfo? y)
        {
            if (ReferenceEquals(x, y))
            {
                return true;
            }

            if (x is null || y is null)
            {
                return false;
            }

            return SymbolEqualityComparer.Default.Equals(x.ClassSymbol, y.ClassSymbol)
                && SymbolEqualityComparer.Default.Equals(x.ConstantsType, y.ConstantsType);
        }

        public int GetHashCode(TargetInfo? obj)
        {
            if (obj is null)
            {
                return 0;
            }

            var hashCode = 17;
            hashCode = (hashCode * 31) + SymbolEqualityComparer.Default.GetHashCode(obj.ClassSymbol);
            hashCode = (hashCode * 31) + SymbolEqualityComparer.Default.GetHashCode(obj.ConstantsType);
            return hashCode;
        }
    }
}
