using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BQuery.SourceGenerators;

[Generator]
public sealed class WindowEventsGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "BQuery.GenerateWindowEventsAttribute";
    private const string HandlerAttributeMetadataName = "BQuery.WindowEventHandlerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (generatorContext, _) => GetTarget(generatorContext))
            .Where(static target => target is not null);

        context.RegisterSourceOutput(targets, static (productionContext, target) =>
        {
            if (target is null)
            {
                return;
            }

            var source = GenerateSource(target);
            if (source is null)
            {
                return;
            }

            productionContext.AddSource(
                $"{target.HintName}.WindowEvents.g.cs",
                SourceText.From(source, Encoding.UTF8));
        });
    }

    private static TargetInfo? GetTarget(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        foreach (var attribute in context.Attributes)
        {
            if (attribute.AttributeClass?.ToDisplayString() != AttributeMetadataName)
            {
                continue;
            }

            if (attribute.ConstructorArguments.Length != 1)
            {
                continue;
            }

            if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol constantsType)
            {
                continue;
            }

            var events = GetEvents(constantsType);
            return new TargetInfo(classSymbol, events, GetHintName(classSymbol));
        }

        return null;
    }

    private static List<WindowEventInfo> GetEvents(INamedTypeSymbol constantsType)
    {

        var events = new List<WindowEventInfo>();

        foreach (var member in constantsType.GetMembers().OfType<IFieldSymbol>())
        {
            if (!member.IsStatic || member.Name == "All")
            {
                continue;
            }

            var attribute = member.GetAttributes()
                .FirstOrDefault(static attr => attr.AttributeClass?.ToDisplayString() == HandlerAttributeMetadataName);

            if (attribute is null)
            {
                continue;
            }

            if (attribute.ConstructorArguments.Length is < 1 or > 2)
            {
                continue;
            }

            if (attribute.ConstructorArguments[0].Value is not ITypeSymbol arg1Type)
            {
                continue;
            }

            ITypeSymbol? arg2Type = null;
            if (attribute.ConstructorArguments.Length == 2)
            {
                if (attribute.ConstructorArguments[1].Value is not ITypeSymbol secondType)
                {
                    continue;
                }

                arg2Type = secondType;
            }

            events.Add(new WindowEventInfo(member.Name, arg1Type, arg2Type));
        }

        return events;
    }

    private static string? GenerateSource(TargetInfo target)
    {
        if (target.Events.Count == 0)
        {
            return null;
        }

        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat;
        var targetNamespace = target.ClassSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : target.ClassSymbol.ContainingNamespace.ToDisplayString();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");

        if (targetNamespace is not null)
        {
            builder.Append("namespace ").Append(targetNamespace).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public partial class ").Append(target.ClassSymbol.Name).AppendLine();
        builder.AppendLine("{");

        foreach (var windowEvent in target.Events)
        {
            AppendField(builder, windowEvent, typeFormat);
        }

        builder.AppendLine();

        foreach (var windowEvent in target.Events)
        {
            AppendMembers(builder, windowEvent, typeFormat);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendField(StringBuilder builder, WindowEventInfo windowEvent, SymbolDisplayFormat typeFormat)
    {
        builder.Append("    private readonly EventSlot<")
            .Append(windowEvent.ArgumentType1.ToDisplayString(typeFormat));

        if (windowEvent.ArgumentType2 is not null)
        {
            builder.Append(", ")
                .Append(windowEvent.ArgumentType2.ToDisplayString(typeFormat));
        }

        builder.Append("> ")
            .Append(windowEvent.SlotName)
            .AppendLine(" = new();");
    }

    private static void AppendMembers(StringBuilder builder, WindowEventInfo windowEvent, SymbolDisplayFormat typeFormat)
    {
        var eventType = windowEvent.ArgumentType2 is null
            ? $"Action<{windowEvent.ArgumentType1.ToDisplayString(typeFormat)}>"
            : $"Action<{windowEvent.ArgumentType1.ToDisplayString(typeFormat)}, {windowEvent.ArgumentType2.ToDisplayString(typeFormat)}>";
        var asyncEventType = windowEvent.ArgumentType2 is null
            ? $"Func<{windowEvent.ArgumentType1.ToDisplayString(typeFormat)}, Task>"
            : $"Func<{windowEvent.ArgumentType1.ToDisplayString(typeFormat)}, {windowEvent.ArgumentType2.ToDisplayString(typeFormat)}, Task>";

        builder.Append("    /// <summary>").AppendLine();
        builder.Append("    /// Current-scope window event for <c>")
            .Append(windowEvent.MemberName)
            .AppendLine("</c>.")
            .AppendLine("    /// </summary>");
        builder.Append("    public event ").Append(eventType).Append("? ").Append(windowEvent.MemberName).AppendLine();
        builder.AppendLine("    {");
        builder.Append("        add => ").Append(windowEvent.SlotName).AppendLine(".Sync += value;");
        builder.Append("        remove => ").Append(windowEvent.SlotName).AppendLine(".Sync -= value;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append("    /// <summary>").AppendLine();
        builder.Append("    /// Current-scope asynchronous window event for <c>")
            .Append(windowEvent.MemberName)
            .AppendLine("</c>.")
            .AppendLine("    /// </summary>");
        builder.Append("    public event ").Append(asyncEventType).Append("? ").Append(windowEvent.MemberName).AppendLine("Async");
        builder.AppendLine("    {");
        builder.Append("        add => ").Append(windowEvent.SlotName).AppendLine(".Async += value;");
        builder.Append("        remove => ").Append(windowEvent.SlotName).AppendLine(".Async -= value;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    [JSInvokable]");
        builder.Append("    public Task Window").Append(windowEvent.InvocationSuffix).Append("(");

        if (windowEvent.ArgumentType2 is null)
        {
            builder.Append(windowEvent.ArgumentType1.ToDisplayString(typeFormat)).Append(" e");
            builder.Append(") => ").Append(windowEvent.SlotName).AppendLine(".InvokeAsync(e);");
        }
        else
        {
            builder.Append(windowEvent.ArgumentType1.ToDisplayString(typeFormat)).Append(" arg1, ");
            builder.Append(windowEvent.ArgumentType2.ToDisplayString(typeFormat)).Append(" arg2");
            builder.Append(") => ").Append(windowEvent.SlotName).AppendLine(".InvokeAsync(arg1, arg2);");
        }

        builder.AppendLine();
    }

    private static string GetHintName(INamedTypeSymbol classSymbol)
    {
        var parts = new Stack<string>();
        ISymbol? current = classSymbol;

        while (current is INamedTypeSymbol namedType)
        {
            parts.Push(namedType.Name);
            current = namedType.ContainingType;
        }

        if (!classSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            parts.Push(classSymbol.ContainingNamespace.ToDisplayString().Replace('.', '_'));
        }

        return string.Join(".", parts);
    }

    private sealed class TargetInfo
    {
        public TargetInfo(INamedTypeSymbol classSymbol, List<WindowEventInfo> events, string hintName)
        {
            ClassSymbol = classSymbol;
            Events = events;
            HintName = hintName;
        }

        public INamedTypeSymbol ClassSymbol { get; }

        public List<WindowEventInfo> Events { get; }

        public string HintName { get; }
    }

    private sealed class WindowEventInfo
    {
        public WindowEventInfo(string memberName, ITypeSymbol argumentType1, ITypeSymbol? argumentType2)
        {
            MemberName = memberName;
            ArgumentType1 = argumentType1;
            ArgumentType2 = argumentType2;
            InvocationSuffix = memberName.StartsWith("On", StringComparison.Ordinal) ? memberName.Substring(2) : memberName;
            SlotName = "_" + char.ToLowerInvariant(InvocationSuffix[0]) + InvocationSuffix.Substring(1);
        }

        public string MemberName { get; }

        public string InvocationSuffix { get; }

        public string SlotName { get; }

        public ITypeSymbol ArgumentType1 { get; }

        public ITypeSymbol? ArgumentType2 { get; }
    }
}
